### ISSUE TITLE
Content Machines card: Title/Subtitle/Category mismatch

### ISSUE THREAD

**Issue by tobias-zucali** [Grand-Garage/webapp#27]
https://grandgarage.eu/de/machines/

Sometimes the main title matches the category ("Elektronik und IoT","3D Druck"), sometimes it is the product name, sometimes something entirely different, sometimes multiple machines are contained in one card. We need clear rules for that.

Recommendation:
- only one user defined title which should be the product name
- subtitle should always be the category name

**Comment by murcoder** [comment]
done
