### ISSUE TITLE
"This page can't load Google Maps correctly." - "Only for dev purposes"

### ISSUE THREAD

**Issue by KargJonas** [Grand-Garage/webapp#32]
Happened to stumble upon this in https://grandgarage.eu/de/kontakt
The map is covered with the message "Only for dev purposes". Seems like you're using a development version of the Google Maps API :sweat_smile:

Console errors:
![image](https://user-images.githubusercontent.com/30984652/62812648-f79d7480-bb06-11e9-8823-2c559c26a8e7.png)

**Comment by doebi** [comment]
Thanks for Reporting!

Seems like our free trial is expired. Gonna take care of it!

**Comment by doebi** [comment]
Deployed a temporal fix for that.
